# Generated by Django 4.2 on 2025-07-06 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_delete_shoppingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_code',
            field=models.CharField(blank=True, help_text='Уникальный код для короткой ссылки на рецепт', max_length=6, null=True, unique=True, verbose_name='Код короткой ссылки'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipe', verbose_name='рецепт'),
        ),
    ]
