# Generated by Django 4.2 on 2025-06-27 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_subscribers', to=settings.AUTH_USER_MODEL, verbose_name='на кого')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='кто')),
            ],
            options={
                'verbose_name': 'подписка',
                'verbose_name_plural': 'подписки',
            },
        ),
    ]
